/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package librarymanagement2;

import javax.swing.JFrame;

/**
 *
 * @author Aayush kumar
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        student = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        booksavailable = new javax.swing.JButton();
        issue = new javax.swing.JButton();
        bookreturn = new javax.swing.JButton();
        fine = new javax.swing.JButton();
        lost = new javax.swing.JButton();
        ebook = new javax.swing.JButton();
        grievance = new javax.swing.JButton();
        rules = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        Enews = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        student.setBackground(javax.swing.UIManager.getDefaults().getColor("Component.disabledBorderColor"));
        student.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        student.setText("Add Student");
        student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentActionPerformed(evt);
            }
        });
        getContentPane().add(student, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 150, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("WELCOME ADMIN!");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 170, 40));

        booksavailable.setBackground(javax.swing.UIManager.getDefaults().getColor("Component.disabledBorderColor"));
        booksavailable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        booksavailable.setText("Books available");
        booksavailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booksavailableActionPerformed(evt);
            }
        });
        getContentPane().add(booksavailable, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 150, 40));

        issue.setBackground(javax.swing.UIManager.getDefaults().getColor("Component.disabledBorderColor"));
        issue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        issue.setText("Issue Book");
        issue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueActionPerformed(evt);
            }
        });
        getContentPane().add(issue, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 150, 40));

        bookreturn.setBackground(javax.swing.UIManager.getDefaults().getColor("Component.disabledBorderColor"));
        bookreturn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bookreturn.setText("Return Book");
        bookreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookreturnActionPerformed(evt);
            }
        });
        getContentPane().add(bookreturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 150, 40));

        fine.setBackground(javax.swing.UIManager.getDefaults().getColor("Component.disabledBorderColor"));
        fine.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fine.setText("Late Fine");
        fine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fineActionPerformed(evt);
            }
        });
        getContentPane().add(fine, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 150, 40));

        lost.setBackground(javax.swing.UIManager.getDefaults().getColor("Component.disabledBorderColor"));
        lost.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lost.setText("Book Lost");
        lost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lostActionPerformed(evt);
            }
        });
        getContentPane().add(lost, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 150, 40));

        ebook.setBackground(javax.swing.UIManager.getDefaults().getColor("Component.disabledBorderColor"));
        ebook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ebook.setText("E-Book/Journals");
        ebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ebookActionPerformed(evt);
            }
        });
        getContentPane().add(ebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 150, 50));

        grievance.setBackground(javax.swing.UIManager.getDefaults().getColor("Component.disabledBorderColor"));
        grievance.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        grievance.setText("Grievance");
        grievance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grievanceActionPerformed(evt);
            }
        });
        getContentPane().add(grievance, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 150, 50));

        rules.setBackground(javax.swing.UIManager.getDefaults().getColor("Component.disabledBorderColor"));
        rules.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rules.setText("Rules & Regulations");
        rules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rulesActionPerformed(evt);
            }
        });
        getContentPane().add(rules, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 700, 170, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Home Page");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 150, 50));

        logout.setBackground(new java.awt.Color(255, 255, 0));
        logout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 40, 110, 40));

        exit.setBackground(new java.awt.Color(255, 0, 51));
        exit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 40, 100, 40));

        Enews.setBackground(new java.awt.Color(204, 204, 204));
        Enews.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Enews.setText("E-News");
        Enews.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnewsActionPerformed(evt);
            }
        });
        getContentPane().add(Enews, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, 150, 40));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Current Affairs");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 130, 140, 40));

        jButton3.setBackground(new java.awt.Color(153, 255, 51));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("College Website");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 40, 140, 40));

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setText("Contact Us");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 190, 140, 40));

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setText("Payment");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 250, 140, 40));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagement2/11.jpg"))); // NOI18N
        jLabel3.setText("College Website");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -190, 2910, 1450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentActionPerformed
        // TODO add your handling code here:
        new newStudent().setVisible(true);
    }//GEN-LAST:event_studentActionPerformed

    private void booksavailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booksavailableActionPerformed
        // TODO add your handling code here:
        new booksAvail().setVisible(true);
    }//GEN-LAST:event_booksavailableActionPerformed

    private void issueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueActionPerformed
        // TODO add your handling code here:
        new bookisuue().setVisible(true);
    }//GEN-LAST:event_issueActionPerformed

    private void bookreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookreturnActionPerformed
        // TODO add your handling code here:
        new bookreturn().setVisible(true);
    }//GEN-LAST:event_bookreturnActionPerformed

    private void fineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fineActionPerformed
        // TODO add your handling code here:
        new bookfine().setVisible(true);
    }//GEN-LAST:event_fineActionPerformed

    private void lostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lostActionPerformed
        // TODO add your handling code here:
        new booklost().setVisible(true);
    }//GEN-LAST:event_lostActionPerformed

    private void ebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ebookActionPerformed
        // TODO add your handling code here:
        new Ebook().setVisible(true);
    }//GEN-LAST:event_ebookActionPerformed

    private void grievanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grievanceActionPerformed
        // TODO add your handling code here:
        new grievance().setVisible(true);
    }//GEN-LAST:event_grievanceActionPerformed

    private void rulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rulesActionPerformed
        // TODO add your handling code here:
        new rules().setVisible(true);
    }//GEN-LAST:event_rulesActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        new login().setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        new first().setVisible(true);
    }//GEN-LAST:event_exitActionPerformed

    private void EnewsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnewsActionPerformed
        // TODO add your handling code here:
        new Enews().setVisible(true);
    }//GEN-LAST:event_EnewsActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new college().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new affair().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new contact().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new payment().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enews;
    private javax.swing.JButton bookreturn;
    private javax.swing.JButton booksavailable;
    private javax.swing.JButton ebook;
    private javax.swing.JButton exit;
    private javax.swing.JButton fine;
    private javax.swing.JButton grievance;
    private javax.swing.JButton issue;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton logout;
    private javax.swing.JButton lost;
    private javax.swing.JButton rules;
    private javax.swing.JButton student;
    // End of variables declaration//GEN-END:variables
}
